/*
  HelloSmartFont.ino - Example for SmartFont Library
*/

#include <Arduino.h>
#include <SmartFont.h>
// #include "fonts/your_font.h" // You need a font file generated by the tool

// Dummy callbacks for compilation example
void drawPixel(int16_t x, int16_t y) {
  // Implement your display draw pixel here
  // display.drawPixel(x, y, 1);
}

void clearPixel(int16_t x, int16_t y) {
  // Implement your display clear pixel here
  // display.drawPixel(x, y, 0);
}

SmartFont myFont(drawPixel, clearPixel);

void setup() {
  Serial.begin(115200);

  // Initialize your display driver here

  // myFont.setFont(&font_name); // Set your font
  myFont.setPos(0, 0);
  myFont.print("Hello SmartFont");
}

void loop() {}
